server:
  port: 8081

spring:
  datasource:
    username: root
    password: root

    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/split?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC

mybatis:
  type-aliases-package: com.example.domain
  mapper-locations: classpath:/mappers/*.xml
logging:
  config: classpath:log.xml
  file:
    path: F:/log
